name = "auth-system-worker"
main = "index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "users-db"
database_id = "b3ad23cf-64b2-488b-9371-0cd4bd398156"

[build]
command = "npm run build"

[vars]
ENVIRONMENT = "production"

